package:
 name: sherpa
 version: 4.9.1

source:
 url: https://github.com/sherpa/sherpa/archive/4.9.1.tar.gz

build:
 number: 0
 script_env:
     - F90 # [osx]
 entry_points:
  - sherpa_test = sherpa:clitest
  - sherpa_smoke = sherpa:smoke

requirements:
 build:
  - python 3.6.0
  - numpy 1.11.*
  - setuptools
  - libgcc 4.8.*
  - libgfortran
  - six

 run:
  - python 3.6.0
  - numpy >1.11
  - setuptools
  - pytest
  - libgcc 4.8.*
  - libgfortran 
  - six

about:
 home: http://cxc.cfa.harvard.edu/sherpa/
 summary: Sherpa is the CIAO modeling and fitting application. It enables the user to construct complex models from simple definitions and fit those models to data, using a variety of statistics and optimization methods
 license: GPLv3

